version: '3.8'

services:
  # This is your Database
  db:
    build: .
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mi@1122@ro
      POSTGRES_DB: test_db
    ports:
      - "5433:5432" # 5433 avoids clashing with a native Postgres service already bound to 5432 on this machine
    volumes:
      - pgdata:/var/lib/postgresql/data # This keeps your tables alive if the container stops

volumes:
  pgdata: