version: '3.8'

services:
  # This is your Database
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mi@1122@ro
      POSTGRES_DB: test_db
    ports:
      - "5432:5432" # This allows DBeaver on your laptop to talk to the DB inside Docker
    volumes:
      - pgdata:/var/lib/postgresql/data # This keeps your tables alive if the container stops

volumes:
  pgdata: